entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

providers:
  docker:
    network: gignet
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  myresolver:
    acme:
      email: ${EMAIL}
      storage: /letsencrypt/acme.json
      tlsChallenge: true

log:
  level: DEBUG
  filePath: "./traefik-logs/traefik.log"
  format: json
